env: "production"
mysql:
  username: "root"
  password: ""
  addr: "localhost:3306"
  db_name: "mercari"
redis:
  addr: "localhost:6379"
mercari:
  client_id: "x6Bd3227EJAZ94B0PWIYXMttbwyVlURP"
  client_secret: "lyQCWHIurdhwqTEjk492VwxBhyO0P6YG"
  callback_url: "https://b4u-req-api.buynship.com/api/callback/mercari/login/"
hmac_secret: "4i8bcy1d-hagm-nfaj-vze5-zzezywp531ro"
otel:
  endpoint: "ec2-user-tempo-1:4317"